### ISSUE TITLE
ruby 2.1.2

### ISSUE THREAD

**Issue by MartinRaskovsky** [mikelarkin/contestapp#6]
Section **Installing Ruby** of _Shopify Application Development_ says:
install Ruby with:
    rvm install 2.1.2

Heroku recommends using the latest supported Ruby version.
so the following command when deploying Heroku fails:

    git push heroku master 

Questions:
1 - Which versions of Ruby/rails you recommend to use?
2 - Since the published screwed up the files on their site, in particular shopify_integration.rb is corrupt, would the following file be compatible with the versions in question (1) above ? 

    https://github.com/mikelarkin/contestapp/blob/chapter_03/app/services/shopify_integration.rb

Thank you 

martinR

**Comment by mikelarkin** [comment]
Good questions! 

1) Try Ruby 2.2.6 (I'll try that as well and update the repo)
2) Yes, I've reached out to them several times but they don't seem to do anything.  The files here on Github are meant to mirror (or improve upon) the book.

**Comment by MartinRaskovsky** [comment]
Thank you Mike. Will use Ruby 2.2.6 Rails 4.0.3 and will let you know the outcome.

**Comment by MartinRaskovsky** [comment]
Mike, using Ruby 2.2.6 Rails 4.0.3 solved the problem initially described, i.e:  Heroku now works

I found and solved the following issues, I thought you had to know:

**Issue 1:**
after: 

    $ gem install rails -v 4.0.3 --no-ri --no-rdoc

before: 

    $ rails new .

Had to do:

    $ upgraded bundler via: gem install bundler --pre

**Issue 2:**

    $ rails generate controller Dashboard index

produced the following warning: 

    .rvm/gems/ruby-2.2.6@contestapp/gems/activesupport-4.0.3/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now

fixed replacing:

    def parse(str, now=now) 

by:

    def parse(str, xnow=now) 

and replacing now for xnow throught the body of parse

**Issue 3:**

    $ heroku create contestapp

produced: ▸    Name is already taken

I used instead: 

    $ heroku create

and heroku responded: 

    https://nameless-hollows-89102.herokuapp.com/ | https://git.heroku.com/nameless-hollows-89102.git

**Issue 4:**
running 
  
    $heroku open

now works openinng a web page that contains:

    Heroku | Welcome to your new app!

I am assuming that the with the above issue 4, the problem is now solved.

thank you

martinR

**Comment by MartinRaskovsky** [comment]
Mike, did you try Ruby 2.2.6 with your chapter 3 ?

I did, and manage to proceed, however still in chapter 3 I found the following:

Issues with integer instead of bigint in several _id column.
Solved by adding a migrate with:

    change_column :products, :shopify_product_id, :bigint
    change_column :variants, :product_id, :bigint
    change_column :variants, :shopify_variant_id, :bigint
    change_column :orders, :shopify_order_id, :bigint
    change_column :order_items, :order_id, :bigint
    change_column :order_items, :variant_id, :bigint
    change_column :order_items, :shopify_product_id, :bigint
    change_column :order_items, :shopify_variant_id, :bigint 
    change_column :contests, :product_id, :bigint
    change_column :contests, :order_id, :bigint

In your book, the rails command:

    g model Contests ... 

should be enumerating 

    product_name:string 

but it does not.


I also have a problem when deploying to a production environment cia Heroku at the end of chapter 3. When clicking on Orders I get an error. The Heroku log shows:

    Starting process with command `bin/rails server -p 9880 -e production`

    [2017-09-16 15:54:00] INFO  WEBrick 1.3.1
    [2017-09-16 15:54:00] INFO  ruby 2.2.6 (2016-11-15) [x86_64-linux]
    pid=4 port=9880
    State changed from starting to up
    at=info method=GET path="/orders" host=mrcontestapp.herokuapp.com request_id=3e8fad73-584d-4dff-896a-932f1f416afb fwd="176.227.133.59" dyno=web.1 connect=0ms service=81ms status=304 bytes=810 protocol=https
    => Booting WEBrick
    => Rails 4.0.3 application starting in production on http://0.0.0.0:9880
    => Run `rails server -h` for more startup options
    => Ctrl-C to shutdown server
    Started GET "/orders" for 176.227.133.59 at 2017-09-16 15:54:19 +0000
    Started GET "/orders" for 176.227.133.59 at 2017-09-16 15:54:19 +0000
    The PGconn, PGresult, and PGError constants are deprecated, and will be
    removed as of version 1.0.
    
    You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
    
    Called from /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
    Processing by OrdersController#index as HTML
    Processing by OrdersController#index as HTML
      Rendered orders/index.html.erb within layouts/application (10.3ms)
      Rendered orders/index.html.erb within layouts/application (10.3ms)

    Started GET "/orders/import" for 176.227.133.59 at 2017-09-16 15:54:23 +0000
    Started GET "/orders/import" for 176.227.133.59 at 2017-09-16 15:54:23 +0000
    Processing by OrdersController#import as HTML
    Processing by OrdersController#import as HTML
    Completed 500 Internal Server Error in 1603ms
    Completed 500 Internal Server Error in 1603ms
    
    NoMethodError (undefined method `year' for nil:NilClass):
      app/services/shopify_integration.rb:104:in `block in import_orders'
      app/services/shopify_integration.rb:96:in `import_orders'
      app/controllers/orders_controller.rb:82:in `block in import'
      app/controllers/orders_controller.rb:78:in `import'

Googling the error message:

    NoMethodError (undefined method `year' for nil:NilClass):

Shows lots of issues with reference to a bug in Rails, which should have been fixed in
